-- Fixes discovered while wiring up loadData()/saveData():
--
-- 1. products/prices were missing fields the app actually uses (variants,
--    per-variant markup overrides, subcategory, product image, variantIdx
--    on price entries). Without these, variant-based products would
--    round-trip through Supabase with silently dropped data.
--
-- 2. The fast-cut saveData() keeps the app's existing client-side nextX
--    counters (nextPriceId, nextStockLogId, etc.) to avoid touching every
--    call site that assigns an id synchronously before any network
--    round-trip. That means inserts need to supply an explicit id, which
--    GENERATED ALWAYS AS IDENTITY rejects. Switching to GENERATED BY
--    DEFAULT allows an explicit id when the app provides one, while still
--    auto-assigning if it's ever omitted.

alter table products
  add column subcategory text,
  add column image text,
  add column type text not null default 'simple',
  add column variant_attributes jsonb,
  add column variants jsonb;

alter table prices
  add column variant_idx text;

alter table prices alter column id set generated by default;
alter table customer_debt_log alter column id set generated by default;
alter table stock_log alter column id set generated by default;
alter table cash_txns alter column id set generated by default;
alter table saved_quotes alter column id set generated by default;
alter table purchase_invoices alter column id set generated by default;
