-- External sales agents: deliberately NOT shop_members.
--
-- Every existing price-book table (suppliers, prices, saved_quotes,
-- customers, ...) carries a blanket "shop members full access" policy --
-- any member sees everything. Agents need the opposite: they must never
-- see supplier identity, other clients' orders, or raw cost/markup data,
-- and other agents' clients must stay invisible to them too. Keeping
-- agents out of shop_members entirely means none of those ~12 existing
-- policies need to be touched or re-audited -- an agent simply has zero
-- access to anything not explicitly granted below, by construction.
--
-- Anything an agent needs that would otherwise require exposing raw
-- table data (product cost/markup, supplier identity behind a
-- promotion) is served through a service-role Edge Function instead of
-- direct table access, so there's no column-level redaction to get
-- subtly wrong in RLS.

create table agents (
  shop_id uuid not null references shops(id) on delete cascade,
  id text not null,
  user_id uuid references auth.users on delete set null,
  name text not null, phone text, email text,
  payment_term text not null default 'prepay' check (payment_term in ('prepay', 'pay_on_delivery')),
  unavailable boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  primary key (shop_id, id)
);
create unique index agents_shop_user_unique on agents(shop_id, user_id) where user_id is not null;

alter table agents enable row level security;

-- Membership-style helpers, mirroring is_shop_member()/is_shop_admin().
create or replace function is_shop_agent(p_shop_id uuid)
returns boolean
language sql security definer stable set search_path = public
as $$
  select exists (select 1 from agents where shop_id = p_shop_id and user_id = auth.uid());
$$;

create or replace function current_agent_id(p_shop_id uuid)
returns text
language sql security definer stable set search_path = public
as $$
  select id from agents where shop_id = p_shop_id and user_id = auth.uid();
$$;

-- Admins manage the roster (invite, view, adjust payment terms). An agent
-- can read their own row -- to see their own payment term in-app -- but
-- there's deliberately no update policy for the agent themselves;
-- payment_term is a trust setting only an admin should be able to change.
create policy "admins manage agents" on agents
  for all using (is_shop_admin(shop_id)) with check (is_shop_admin(shop_id));
create policy "agent views own row" on agents
  for select using (user_id = auth.uid());

-- ---------------------------------------------------------------------
-- Private client roster -- the whole point of the identity-hiding design.
-- Only the owning agent can ever read or write these; there is no
-- shop/admin-facing policy on this table at all. A shop-visible delivery
-- address (when relevant) is carried separately, directly on the order's
-- own payload -- see saved_quotes below -- rather than by granting any
-- cross-table exception into this table, which would have meant either
-- leaking the client's name too or relying on fragile column-level RLS.
create table agent_clients (
  shop_id uuid not null references shops(id) on delete cascade,
  id bigint generated by default as identity,
  agent_id text not null,
  name text not null, phone text, location text,
  created_at timestamptz not null default now(),
  primary key (shop_id, id),
  foreign key (shop_id, agent_id) references agents(shop_id, id) on delete cascade
);
create index agent_clients_agent_idx on agent_clients(shop_id, agent_id);

alter table agent_clients enable row level security;
create policy "agent manages own clients" on agent_clients
  for all using (agent_id = current_agent_id(shop_id)) with check (agent_id = current_agent_id(shop_id));

-- ---------------------------------------------------------------------
-- Commission cluster: which supplier-promoted products an agent has
-- opted into pushing. Bonus commission is only ever calculated and
-- locked in at the moment of a sale if added_at is already at least the
-- shop's configured wait period old (agent-submit-order's
-- resolveClusterWaitDays(); app-level check, not enforced here) -- so
-- there's nothing to game by starring a high-bonus item right before
-- checkout.
create table agent_clusters (
  shop_id uuid not null references shops(id) on delete cascade,
  agent_id text not null,
  product_id text not null,
  variant_idx text not null default '',
  added_at timestamptz not null default now(),
  primary key (shop_id, agent_id, product_id, variant_idx),
  foreign key (shop_id, agent_id) references agents(shop_id, id) on delete cascade,
  foreign key (shop_id, product_id) references products(shop_id, id) on delete cascade
);

alter table agent_clusters enable row level security;
create policy "agent manages own cluster" on agent_clusters
  for all using (agent_id = current_agent_id(shop_id)) with check (agent_id = current_agent_id(shop_id));

-- ---------------------------------------------------------------------
-- Supplier-funded product promotions. supplier_id is deliberately never
-- exposed to agents -- there is no agent-facing policy on this table at
-- all. Agents see promotions (minus supplier_id) exclusively through the
-- agent-catalog Edge Function, which reads this table with the
-- service-role key and hand-picks which fields to return.
create table agent_promotions (
  shop_id uuid not null references shops(id) on delete cascade,
  id bigint generated always as identity primary key,
  product_id text not null,
  variant_idx text not null default '',
  supplier_id text,
  bonus_type text not null check (bonus_type in ('percent', 'fixed')),
  bonus_value numeric not null,
  active boolean not null default true,
  starts_at date, ends_at date,
  created_at timestamptz not null default now(),
  foreign key (shop_id, product_id) references products(shop_id, id) on delete cascade,
  foreign key (shop_id, supplier_id) references suppliers(shop_id, id) on delete set null
);
create index agent_promotions_shop_idx on agent_promotions(shop_id);

alter table agent_promotions enable row level security;
create policy "admins manage promotions" on agent_promotions
  for all using (is_shop_admin(shop_id)) with check (is_shop_admin(shop_id));

-- ---------------------------------------------------------------------
-- Per-product agent discount overrides -- blank means "use the shop-wide
-- preset default", same convention as the existing stock_*_markup_*
-- override columns added in 0006. Two independent percentages, since
-- wholesale and retail are two different price bases with their own
-- markups already.
--
-- products had no created_at at all until now -- needed so the agent
-- Explore page can surface "new arrivals". Existing rows get "now" as a
-- one-time backfill (their real creation date was never tracked), which
-- just means nothing already on file shows up as "new" the moment this
-- ships -- exactly the right behavior, since none of it actually is.
alter table products
  add column agent_discount_wholesale_pct numeric,
  add column agent_discount_retail_pct numeric,
  add column created_at timestamptz not null default now();

-- ---------------------------------------------------------------------
-- Narrow, additive policy letting an agent create/read/update ONLY their
-- own orders. The existing "shop members full access" policy on
-- saved_quotes is untouched -- agents were never members, so it already
-- grants them nothing -- this is a second, independent policy layered
-- alongside it (Postgres combines multiple permissive policies with OR),
-- scoped tightly to rows carrying their own agent id in payload.
create or replace function is_order_agent(p_shop_id uuid, p_agent_id text)
returns boolean
language sql security definer stable set search_path = public
as $$
  select p_agent_id is not null and exists (
    select 1 from agents where shop_id = p_shop_id and id = p_agent_id and user_id = auth.uid()
  );
$$;

create policy "agents manage their own orders" on saved_quotes
  for all
  using (is_order_agent(shop_id, payload->>'originAgentId'))
  with check (is_order_agent(shop_id, payload->>'originAgentId'));
