-- MTN Mobile Money + Airtel Money for agent payments.
-- See the design plan for context: agents currently pay the shop
-- entirely off-app (admin manually confirms cash via agentPrepayModal
-- in index.html); this adds a real electronic payment path alongside
-- that unchanged manual fallback.

-- Per-shop, per-provider API credentials. Every table in this app is
-- multi-tenant via shop_id, so each shop needs its own real MTN/Airtel
-- merchant credentials -- these can't be a single global Edge Function
-- secret. `credentials` is kept as jsonb rather than named columns
-- because MTN (subscription key / API user / API key) and Airtel
-- (client id / client secret / merchant id) have different shapes.
-- Locked to admin/owner only, same convention as every other
-- admin-only table (e.g. `agents`, `agent_promotions` in
-- 0012_sales_agents.sql) -- no agent or plain-staff policy at all.
create table shop_payment_providers (
  shop_id uuid not null references shops(id) on delete cascade,
  provider text not null check (provider in ('mtn','airtel')),
  environment text not null default 'sandbox' check (environment in ('sandbox','production')),
  enabled boolean not null default false,
  credentials jsonb not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (shop_id, provider)
);
alter table shop_payment_providers enable row level security;
create policy "admin manages payment providers" on shop_payment_providers
  for all using (is_shop_admin(shop_id)) with check (is_shop_admin(shop_id));

-- One row per payment attempt. external_reference is generated by us
-- and handed to the provider (MTN's X-Reference-Id / Airtel's
-- transaction.id) so a webhook or a status poll can always find its way
-- back to the right row. Only ever written by a service-role Edge
-- Function (agent-initiate-momo-payment, the two webhook functions,
-- check-momo-payment-status) -- there is deliberately no insert/update
-- policy for the `authenticated` role, only a select policy so the
-- agent's own app can poll status directly.
create table agent_mobile_payments (
  id bigint generated always as identity primary key,
  shop_id uuid not null references shops(id) on delete cascade,
  agent_id text not null,
  order_id bigint references saved_quotes(id) on delete set null,
  provider text not null check (provider in ('mtn','airtel')),
  phone text not null,
  amount numeric not null,
  currency text not null default 'UGX',
  external_reference uuid not null unique,
  provider_transaction_id text,
  status text not null default 'pending' check (status in ('pending','successful','failed','cancelled','timeout')),
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (shop_id, agent_id) references agents(shop_id, id) on delete cascade
);
create index agent_mobile_payments_shop_idx on agent_mobile_payments(shop_id);
alter table agent_mobile_payments enable row level security;
create policy "agent views own mobile payments" on agent_mobile_payments
  for select using (agent_id = current_agent_id(shop_id));
