-- Moves the remaining id counters off the client, finishing what 0032
-- started.
--
-- 0032 covered the four ids a human used to type (product, supplier,
-- customer, staff). It left the numeric surrogate ids alone: prices, stock
-- log entries, cash transactions, saved quotes, purchase invoices and
-- customer debt log entries all still get their id from
-- `data.nextXId++`, a counter derived on load as max(existing id) + 1.
--
-- Two admins therefore read the same number and both write it. The rows
-- sync by upsert, so the second silently overwrites the first -- no error,
-- no conflict, one record simply gone. On cash_txns and customer_debt_log
-- that is money disappearing from the books; on saved_quotes it is a whole
-- order. It also reuses the ids of deleted rows, so a stale payment link
-- (payments[].cashTxnId) can end up pointing at an unrelated transaction.
--
-- BLOCK allocation rather than 0032's one-id-per-call, because these are
-- issued from synchronous code deep inside the app -- addCashPayment() is
-- called mid-loop while allocating a supplier payment across invoices, and
-- making it await would ripple through every caller. Instead each client
-- reserves a small contiguous run up front and hands them out locally. The
-- reservation is atomic, so two clients can never hold overlapping runs,
-- and the call sites stay synchronous.
--
-- The cost is gaps: a session that reserves ten and uses three leaves seven
-- unused. For surrogate keys that is free. It is visible on saved_quotes
-- and purchase_invoices, whose ids are formatted into the INV-/PINV-
-- document numbers, so those numbers will now skip. Gaps in an invoice
-- sequence are ordinary in accounting -- a reserved-but-unused number is
-- auditable, and it stays strictly increasing -- but it is a real change in
-- what the shop sees, hence the small block size.

-- supplier_commissions was created `generated always as identity` (0020)
-- while every other table the client writes was moved to `by default`
-- (0002). The client supplies its own id for this table too, so an insert
-- here would be rejected outright with "cannot insert a non-DEFAULT value".
-- Latent today -- nothing in the admin app creates a supplier commission --
-- but it would fail on the first attempt, so bring it in line now.
alter table supplier_commissions alter column id set generated by default;

-- Seed each counter from what already exists, so the first block starts
-- above every current row. Kinds are namespaced `row:` to keep them clear
-- of 0032's text-id kinds sharing this table.
insert into entity_id_counters (shop_id, kind, last_issued)
select shop_id, 'row:price', max(id) from prices group by shop_id
on conflict (shop_id, kind) do nothing;

insert into entity_id_counters (shop_id, kind, last_issued)
select shop_id, 'row:stock_log', max(id) from stock_log group by shop_id
on conflict (shop_id, kind) do nothing;

insert into entity_id_counters (shop_id, kind, last_issued)
select shop_id, 'row:cash_txn', max(id) from cash_txns group by shop_id
on conflict (shop_id, kind) do nothing;

insert into entity_id_counters (shop_id, kind, last_issued)
select shop_id, 'row:saved_quote', max(id) from saved_quotes group by shop_id
on conflict (shop_id, kind) do nothing;

insert into entity_id_counters (shop_id, kind, last_issued)
select shop_id, 'row:purchase_invoice', max(id) from purchase_invoices group by shop_id
on conflict (shop_id, kind) do nothing;

insert into entity_id_counters (shop_id, kind, last_issued)
select shop_id, 'row:debt_log', max(id) from customer_debt_log group by shop_id
on conflict (shop_id, kind) do nothing;

-- Reserves a run of `p_count` ids for each requested kind and returns the
-- FIRST id of each run, as {kind: first}. One round trip covers every
-- collection, which is what makes this affordable to call on boot.
--
-- p_floors is {kind: n} -- "whatever you do, don't issue at or below n".
-- Same role as 0032's p_floor: it covers rows created while a client was
-- falling back to its local counter, which the seed above cannot know
-- about after the fact.
create or replace function next_row_id_blocks(
  p_shop_id uuid,
  p_kinds text[],
  p_count int default 10,
  p_floors jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  k text;
  n int := greatest(coalesce(p_count, 10), 1);
  v bigint;
  f bigint;
  out jsonb := '{}'::jsonb;
begin
  if not is_shop_member(p_shop_id) then
    raise exception 'Not a member of this shop';
  end if;
  if p_kinds is null or array_length(p_kinds, 1) is null then
    raise exception 'at least one kind is required';
  end if;

  foreach k in array p_kinds
  loop
    if k !~ '^row:[a-z_]+$' then
      raise exception 'unknown row id kind: %', k;
    end if;
    f := coalesce((p_floors ->> k)::bigint, 0);

    -- The ON CONFLICT branch takes a row lock, so concurrent callers
    -- serialise here and their runs cannot overlap.
    insert into entity_id_counters (shop_id, kind, last_issued)
         values (p_shop_id, k, greatest(0, f) + n)
    on conflict (shop_id, kind) do update
            set last_issued = greatest(entity_id_counters.last_issued, f) + n
      returning last_issued into v;

    out := out || jsonb_build_object(k, v - n + 1);
  end loop;

  return out;
end;
$$;

revoke all on function next_row_id_blocks(uuid, text[], int, jsonb) from public;
grant execute on function next_row_id_blocks(uuid, text[], int, jsonb) to authenticated;
