-- The things the shop owns and uses, as opposed to the things it sells.
--
-- A delivery van, a forklift, shelving, a laptop. They are not stock:
-- stock is bought to be sold and leaves through COGS, while these are
-- bought to be USED and leave a little at a time, over years, as
-- depreciation. Until now the app had nowhere to put one, so a van
-- appeared in the cash book as a single large payment in one month and
-- then vanished from the accounts entirely -- no asset on the balance
-- sheet, and a month that looked catastrophic followed by years that
-- looked better than they were.
--
-- Deliberately NOT derived from cash_txns. The purchase is one cash
-- movement; the asset is a separate fact with a life, a method and a
-- residual value that no cash row carries. Linking the two is optional
-- (cash_txn_id) so an asset the shop already owned before it started
-- using this app can still be recorded.
create table fixed_assets (
  -- BY DEFAULT, not ALWAYS: the app assigns row ids synchronously before
  -- any round trip and upserts them (see ROW_ID_KINDS / next_row_id_blocks,
  -- and 0002 which converted the original tables for the same reason).
  -- ALWAYS would reject every insert the client makes.
  id bigint generated by default as identity primary key,
  shop_id uuid not null references shops(id) on delete cascade,
  name text not null,
  category text,
  -- What it cost to get it working, which is not always the invoice: the
  -- delivery and the fitting belong in here too.
  cost numeric not null default 0,
  acquired_on date not null,
  -- 'straight_line' spreads cost less salvage evenly over the life.
  -- 'reducing_balance' charges a percentage of what is left each year, so
  -- it is heavier early -- which is how a vehicle actually loses value.
  method text not null default 'straight_line'
    check (method in ('straight_line', 'reducing_balance')),
  -- Straight line uses life_months. Reducing balance uses rate_pct a year.
  -- The other is null rather than zero, so "not applicable" and "none" do
  -- not look the same.
  life_months integer,
  rate_pct numeric,
  -- What it is expected to be worth at the end. Depreciation never takes
  -- an asset below this.
  salvage numeric not null default 0,
  -- Set when it is sold or scrapped. Depreciation stops on this date and
  -- the difference between proceeds and book value is a gain or a loss.
  disposed_on date,
  disposal_proceeds numeric,
  notes text,
  cash_txn_id bigint,
  created_at timestamptz not null default now()
);
create index fixed_assets_shop_idx on fixed_assets(shop_id);

alter table fixed_assets enable row level security;
create policy "shop members full access" on fixed_assets
  for all using (is_shop_member(shop_id)) with check (is_shop_member(shop_id));

-- The id counter this table's rows are issued from, same block scheme as
-- 0034. Seeded per shop rather than left absent: next_row_id_blocks starts
-- from whatever it finds, and a missing counter would hand the first
-- client id 1 for a table that may already have rows if this migration is
-- ever re-run against a restored database.
insert into entity_id_counters (shop_id, kind, last_issued)
select id, 'row:fixed_asset', 0 from shops
on conflict (shop_id, kind) do nothing;
