-- Money the shop has borrowed.
--
-- Until now a loan arrived as a cash-book receipt categorised "Loan
-- Received" and that was the whole of it: an inflow that looked like
-- income, no liability anywhere, and no record that any of it had to go
-- back. Phase 1 stopped it counting as revenue. This is where it becomes
-- something the shop actually owes.
--
-- TWO KINDS, because both are ordinary here and they are not the same
-- loan at the same rate:
--
--   reducing_balance  interest each month on what is still owed. A bank
--                     term loan. The stated rate is close to the real one.
--   flat              interest for the whole term computed once on the
--                     ORIGINAL principal, then split evenly. Common with
--                     SACCOs and microfinance. "12% flat" over a year is
--                     nearer 22% in effect, because you go on paying
--                     interest on money you have already given back. The
--                     app computes and shows that difference rather than
--                     repeating the number on the paperwork.
--
-- Repayments live in payload.repayments, following purchase_invoices and
-- saved_quotes: a thin column set for what gets queried, a jsonb payload
-- for the list of payments against the document. Each repayment can carry
-- the cash_txn_id it was written to the cash book as, so the two can be
-- reconciled and a reversal can find its entry.
create table loans (
  -- BY DEFAULT, not ALWAYS: the client assigns ids synchronously before
  -- any round trip (see ROW_ID_KINDS), and ALWAYS rejects them. Same
  -- reason as 0002 and 0042.
  id bigint generated by default as identity primary key,
  shop_id uuid not null references shops(id) on delete cascade,
  lender text not null,
  principal numeric not null default 0,
  -- Annual, as written on the agreement. What it MEANS depends on method.
  rate_pct numeric not null default 0,
  method text not null default 'reducing_balance'
    check (method in ('reducing_balance', 'flat')),
  term_months integer not null default 12,
  started_on date not null,
  -- Set when the last shilling is paid or the debt is written off. Kept
  -- rather than deleted: a settled loan is part of the shop's history and
  -- its interest still belongs to the months it was charged in.
  closed_on date,
  notes text,
  cash_txn_id bigint,
  payload jsonb,
  created_at timestamptz not null default now()
);
create index loans_shop_idx on loans(shop_id);

alter table loans enable row level security;
create policy "shop members full access" on loans
  for all using (is_shop_member(shop_id)) with check (is_shop_member(shop_id));

-- The id counter these rows are issued from, same block scheme as 0034.
insert into entity_id_counters (shop_id, kind, last_issued)
select id, 'row:loan', 0 from shops
on conflict (shop_id, kind) do nothing;
