-- What the shop owes its people and its landlord.
--
-- Until now "Rent" and "Salaries & Wages" existed only as cash-book
-- expense categories: you could file a payment after the fact and it
-- landed in operating costs, correctly. What was missing was everything
-- BEFORE the payment. Staff carried no pay rate, so payroll could only
-- be typed as a lump sum and never checked. There was no rent agreement,
-- so nothing knew what was due or when. And nothing in the app was ever
-- "owed but unpaid" except a loan -- so rent five days late, or a month
-- of wages already worked, was invisible.
--
-- THE MODEL IS A COMMITMENT AND A DUE.
--
--   a commitment  a rent agreement, or a staff member's pay rate. What
--                 is owed, how often, from when.
--   a due         one month's worth of one commitment. Generated from
--                 it, then paid off. This is the thing that can be
--                 overdue, part-paid, or still unknown.
--
-- Dues are stored rather than derived, for two reasons. A daily-paid
-- worker's month is not knowable without someone entering the days, so
-- there is real input to keep. And the RATE IS SNAPSHOT ONTO THE DUE at
-- the moment it is generated: giving somebody a raise in August must not
-- silently rewrite what July cost. Same reason a loan keeps its
-- repayments when its terms are edited.

-- ---------------------------------------------------------------------
-- What each staff member is paid.
--
-- NULL, NOT ZERO. A staff member with no rate set has not been given a
-- rate of nothing -- they are somebody nobody has got round to setting
-- up, and the payroll screen has to say so rather than quietly costing
-- them at zero and reporting a month that is short by one person's
-- wages. Every existing row starts here, so this is the common case on
-- day one, not an edge.
-- ---------------------------------------------------------------------
alter table staff
  add column pay_basis text
    check (pay_basis is null or pay_basis in ('monthly', 'daily')),
  add column pay_rate numeric
    check (pay_rate is null or pay_rate >= 0);

comment on column staff.pay_basis is
  'monthly = pay_rate is a month''s wage; daily = pay_rate is one day''s wage and days worked are entered per month; null = no rate set, which is not the same as a rate of zero.';

-- ---------------------------------------------------------------------
-- Rent. A list rather than a single row: a shop with a lock-up as well
-- as its main premises pays two landlords, and one row would have forced
-- the second to be tracked in somebody's head.
-- ---------------------------------------------------------------------
create table rent_agreements (
  -- BY DEFAULT, not ALWAYS: the client assigns ids synchronously before
  -- any round trip (see ROW_ID_KINDS), and ALWAYS rejects them. Same
  -- reason as 0002, 0042 and 0043.
  id bigint generated by default as identity primary key,
  shop_id uuid not null references shops(id) on delete cascade,
  premises text not null,
  landlord text,
  amount numeric not null default 0,
  -- Day of the month the rent falls due. Capped at 28 so that every
  -- month has one: a due day of the 30th would silently skip February.
  due_day integer not null default 1 check (due_day between 1 and 28),
  -- YYYY-MM. Dues are never generated for a month before the agreement
  -- started, so taking on premises in June does not invent five months
  -- of arrears.
  start_month text not null,
  -- Set when the tenancy ends. Kept rather than deleted: the rent
  -- already paid under it belongs to the months it was paid in.
  end_month text,
  notes text,
  created_at timestamptz not null default now()
);
create index rent_agreements_shop_idx on rent_agreements(shop_id);

alter table rent_agreements enable row level security;
create policy "shop members full access" on rent_agreements
  for all using (is_shop_member(shop_id)) with check (is_shop_member(shop_id));

-- ---------------------------------------------------------------------
-- One month of one commitment.
-- ---------------------------------------------------------------------
create table dues (
  id bigint generated by default as identity primary key,
  shop_id uuid not null references shops(id) on delete cascade,
  kind text not null check (kind in ('rent', 'wage')),
  -- A staff.id (text) or a rent_agreements.id (bigint), held as text so
  -- one table can carry both. Not a foreign key for that reason; the
  -- app resolves it, and a due whose commitment has been deleted still
  -- has to show what was owed and paid.
  ref_id text not null,
  -- YYYY-MM, the month the money belongs to.
  period text not null,
  due_date date not null,
  -- NULL means NOT YET KNOWN, and is the whole reason this column is
  -- nullable. A daily-paid worker's month cannot be costed until
  -- somebody counts the days; reading that as zero would report a
  -- payroll that is confidently wrong and short. The screen shows these
  -- apart from the total rather than folding them into it.
  amount numeric check (amount is null or amount >= 0),
  -- Daily wages only. Same rule: null is uncounted, 0 is a month
  -- somebody genuinely did not work.
  days numeric check (days is null or days >= 0),
  -- What the commitment said WHEN THIS DUE WAS RAISED. A raise in August
  -- must not rewrite what July cost.
  rate numeric not null default 0,
  paid numeric not null default 0 check (paid >= 0),
  notes text,
  -- payments: [{date, amount, account, cashTxnId}] -- following loans
  -- and purchase_invoices. Each carries the cash-book entry it was
  -- written as, so a payment can be reconciled and a reversal can find
  -- and remove its entry.
  payload jsonb,
  created_at timestamptz not null default now(),
  -- One due per commitment per month. This is what makes generating a
  -- month idempotent: opening the payroll screen twice in a morning must
  -- not raise the rent twice.
  unique (shop_id, kind, ref_id, period)
);
create index dues_shop_idx on dues(shop_id);
create index dues_period_idx on dues(shop_id, period);

alter table dues enable row level security;
create policy "shop members full access" on dues
  for all using (is_shop_member(shop_id)) with check (is_shop_member(shop_id));

-- The id counters these rows are issued from, same block scheme as 0034.
insert into entity_id_counters (shop_id, kind, last_issued)
select id, 'row:rent_agreement', 0 from shops
on conflict (shop_id, kind) do nothing;

insert into entity_id_counters (shop_id, kind, last_issued)
select id, 'row:due', 0 from shops
on conflict (shop_id, kind) do nothing;
