-- A media library: an index over the photos already in Storage.
--
-- Photos have lived in the `product-images` bucket since 0005, at
-- {shop_id}/{uuid}.{ext}, with the URL written straight onto whatever
-- referenced them -- a product's `image`, a variant's `image`, a category
-- preset's `image`. That works for showing a picture and for nothing
-- else. A photo is a random UUID: nothing records what it is called,
-- how big it is, when it arrived, or what uses it. So the shop cannot
-- see how much storage it is paying for, cannot reuse a photo it already
-- has, and re-uploads the same picture every time it needs it again.
--
-- These two tables are that index. THE BUCKET REMAINS THE TRUTH about
-- the bytes; this is a catalogue of it, and every row points at an
-- object that is already there.
--
-- WHAT IS DELIBERATELY NOT HERE.
--
--   No usage column. What uses a photo is counted by scanning products,
--   variants and category presets on read. A stored count is a second
--   copy of a fact that already exists, and the app has been bitten by
--   exactly that before (see the debt-drift banner): the moment it can
--   disagree with the thing it describes, it eventually will.
--
--   No unique constraint on sha256. Duplicates are a thing to REPORT,
--   not a thing to make impossible -- a shop already holding the same
--   photo twice must still be able to load its library and be told so.
--   Deduplication happens on upload, by looking first.

-- ---------------------------------------------------------------------
-- Folders. Rows, not storage prefixes.
--
-- Storage prefixes would make a folder part of the object path, so
-- moving a photo between folders would mean copying the bytes and
-- deleting the original -- an expensive, interruptible operation for
-- what the user experiences as a drag. As a row it is one update.
-- ---------------------------------------------------------------------
create table media_folders (
  -- BY DEFAULT, not ALWAYS: the client assigns ids synchronously before
  -- any round trip (see ROW_ID_KINDS), and ALWAYS rejects them. Same
  -- reason as 0002, 0042, 0043 and 0046.
  id bigint generated by default as identity primary key,
  shop_id uuid not null references shops(id) on delete cascade,
  name text not null,
  -- Null is the top level. A folder inside a deleted folder would be
  -- unreachable, so removing a parent re-parents its children rather
  -- than orphaning them -- done in the app, where the user can be told.
  parent_id bigint references media_folders(id) on delete set null,
  created_at timestamptz not null default now()
);
create index media_folders_shop_idx on media_folders(shop_id);

alter table media_folders enable row level security;
create policy "shop members full access" on media_folders
  for all using (is_shop_member(shop_id)) with check (is_shop_member(shop_id));

-- ---------------------------------------------------------------------
-- The photos.
-- ---------------------------------------------------------------------
create table media (
  id bigint generated by default as identity primary key,
  shop_id uuid not null references shops(id) on delete cascade,

  -- The storage object, and the public URL built from it. Both are kept:
  -- `path` is what deletes and moves address, `url` is what every
  -- existing row in products/variants/categories already holds, and
  -- matching on it is how the backfill and the usage count find each
  -- other. Deriving one from the other at read time would work until
  -- the project URL ever changed, and then every reference would miss.
  path text not null,
  url text not null,

  -- What a person calls it. Defaults to the original filename on upload,
  -- because a UUID is not a name anybody can search for.
  name text not null,

  bytes bigint,
  mime text,

  -- SHA-256 of the file's own bytes, so the same picture is recognised
  -- after a rename or a re-download. Nullable: the backfill hashes what
  -- it can fetch, and a photo it cannot reach still belongs in the
  -- library. A null hash simply never matches, which is the safe way to
  -- be wrong -- it uploads a second copy rather than silently reusing
  -- the wrong picture.
  sha256 text,

  folder_id bigint references media_folders(id) on delete set null,
  created_at timestamptz not null default now()
);
create index media_shop_idx on media(shop_id);
create index media_folder_idx on media(shop_id, folder_id);
-- Dedupe is a lookup on every upload, so it gets an index. Not unique:
-- see the note at the top.
create index media_sha_idx on media(shop_id, sha256) where sha256 is not null;
-- The backfill and the usage scan both join on the URL already stored
-- against a product.
create index media_url_idx on media(shop_id, url);

alter table media enable row level security;
create policy "shop members full access" on media
  for all using (is_shop_member(shop_id)) with check (is_shop_member(shop_id));
