-- WhatsApp post history: which product was posted (to Status, or a
-- Channel) on which day, and why it was picked.
--
-- This table is what makes the daily recommendations HONEST. "Not shown
-- recently" is a rotation claim, and a claim needs a record: without
-- this, the picker would recommend the same three best products every
-- single day and the shop's status would go stale in a week. One row per
-- post actually made -- the "Mark as posted" tap, not the suggestion.
--
-- `reason` is the sentence the picker showed when it recommended the
-- product ("12 bags sitting 46 days · margin 23%"). Stored so the
-- history can still say why, months later, after the stock and prices
-- that justified it have moved on. Denormalised `name` for the same
-- reason: the label as it read on the day, safe against renames.

create table wa_posts (
  -- BY DEFAULT, not ALWAYS: client-assigned ids (see ROW_ID_KINDS),
  -- same as 0049 and everything before it.
  id bigint generated by default as identity primary key,
  shop_id uuid not null references shops(id) on delete cascade,
  date date not null,
  product_id text not null,
  -- Integer, deliberately not text: prices.variant_idx being text is the
  -- reason a whole class of === comparisons silently failed (see the
  -- loadData note). Null means the simple product, not variant 0.
  variant_idx integer,
  name text not null,
  reason text,
  created_at timestamptz not null default now()
);
create index wa_posts_shop_date_idx on wa_posts(shop_id, date);

alter table wa_posts enable row level security;
create policy "shop members full access" on wa_posts
  for all using (is_shop_member(shop_id)) with check (is_shop_member(shop_id));

-- The id counter, seeded in the same migration that creates the table --
-- the row-id test sweeps for exactly this pairing (see 0050).
insert into entity_id_counters (shop_id, kind, last_issued)
select id, 'row:wa_post', 0 from shops
on conflict (shop_id, kind) do nothing;
